/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就获得！",
    "All-Knowing": "无所不知",
    "Automate the hiring of employees.": "自动招聘员工。",
    "Buy the 3 second-row Training Upgrades.": "购买 3 个第二排训练升级。",
    "Company Goals": "公司目标",
    "Corporate Loyalist": "企业忠诚者",
    "Daddy Warbucks": "爸爸沃巴克斯",
    "Door-to-Door Charlatan": "上门骗子",
    "Dried-Out Economy": "枯竭的经济",
    "Elected Official": "民选官员",
    "Employers": "雇主",
    "False Happiness": "虚假的幸福",
    "Gain 1 morale.": "获得 1 士气。",
    "Gain 1 training seminar.": "获得 1 次培训研讨会。",
    "Have at least 10 morale.": "至少有 10 士气。",
    "Hire a C-Level.": "聘请 C 级人员。",
    "Hire a Middle Manager.": "聘请中层经理。",
    "Hire a Pocket Politician.": "雇用一名袖珍政治家。",
    "Hire a Privatized Cop.": "聘请私人警察。",
    "Hire a Salesman.": "聘请推销员。",
    "Hire a Shadow Government.": "聘请影子政府。",
    "Hire a Wage Slave.": "雇佣一个工资奴隶。",
    "Hire an Intern.": "聘请实习生。",
    "Hire an Overseer.": "聘请监督者。",
    "Intern": "实习生",
    "Invest with your stocks for the first time.": "第一次用你的股票投资。",
    "It took you {{formatTime(player.timePlayed)}} to fulfill your quota.": "你花了 {{formatTime(player.timePlayed)}} 来完成你的配额。",
    "Joy To The World": "欢乐世界",
    "New World Order": "新世界秩序",
    "Office Drone": "办公无人机",
    "Officer Friendly": "军官友好",
    "Please check the Discord server on your own time to see if you have to keep working (or else you're fired).": "请根据自己的时间检查 Discord 服务器，看看你是否必须继续工作（否则你会被解雇）。",
    "Preparation": "准备",
    "Profits": "利润",
    "Salesman": "推销员",
    "Skeleton Crew": "骷髅船员",
    "Technique": "工艺",
    "Thought Leader": "思想领袖",
    "Unpaid Assistant": "无薪助手",
    "Wage Slave": "工资奴隶",
    "Welcome to Tree, Inc.!": "欢迎来到公司树！",
    "Workforce": "劳动力",
    "You've decided to begin your very own company, to try and make some money. However, you're going to need some help to start production. Why don't you start with hiring that Intern?": "你决定开一家自己的公司，努力赚钱。 但是，您需要一些帮助才能开始生产。 你为什么不从雇佣那个实习生开始呢？",
    "Training": "训练",
    "Your employees just aren't working hard enough. This means that you have to go back to the drawing board! It's time for you to teach your workforce a few things about hard work, dedication, and cooperation.": "您的员工只是工作不够努力。 这意味着你必须回到绘图板上！ 是时候让您的员工了解一些关于努力工作、奉献精神和合作的知识了。",
    "Dedication": "奉献",
    "Government Bribing": "贿赂政府",
    "Longer Work Weeks": "更长的工作周",
    "Middle Managers, C-Levels, and Privatized Cops are 6x as effective.": "中层管理人员、C 级人员和私有化警察的效率是其 6 倍。",
    "Pocket Politicians, Shadow Governments, and Overseers are 8x as effective.": "袖珍政客、影子政府和监督者的效率是其 8 倍。",
    "Promotion": "晋升",
    "Automate the hiring of your employees without having to spend any money.": "无需花钱即可自动招聘员工。",
    "training seminars": "培训班",
    "Triple money gain.": "三倍金钱收益。",
    "Workers, Wage Slaves, and Salesmen are 4x as effective.": "工人、工资奴隶和推销员的效率是前者的 4 倍。",
    "Middle Manager": "中层管理",
    "C-Level": "C级",
    "Privatized Cop": "私营警察",
    "Pocket Politician": "袖珍政客",
    "Overseer": "监工",
    "Shadow Government": "影子政府",
    "Cooperative Effort": "合作努力",
    "Expansion": "扩张",
    "Gain more money based on total employees hired.": "根据雇用的员工总数获得更多的钱。",
    "Gain more money based on training seminars.": "通过培训研讨会获得更多收益。",
    "Innovation": "革新",
    "Unlock 2 new layers.": "解锁 2 个新图层。",
    "Slightly Higher Wages": "略高的工资",
    "stocks": "股票",
    "Training seminars add to the morale base at a reduced rate.": "培训班以较低的速度增加了士气基础。",
    "Unlock 2 new Training Upgrades.": "解锁 2 个新的训练升级。",
    "morale": "士气",
    "Brainstorm Session": "头脑风暴课程",
    "Holiday Vacations": "节假日",
    "Invest 1": "投资 1",
    "investment points, multiplying money gain by": "投资点数，乘以金钱收益",
    "Invest all": "投资全部",
    "Investments": "投资",
    "Morale": "士气",
    "morale": "士气",
    "morale, multiplying money gain by": "士气，将金钱收益乘以",
    "Pep Talks": "鼓舞士气的谈话",
    "As your business grows, you see other companies rise and fall. Why not invest in these growing corporations? You can use your stocks to invest in other companies, gaining investment points (IP). IP gives a big multiplier, but it decays over time.": "随着您的业务增长，您会看到其他公司的兴衰。 为什么不投资这些成长中的公司呢？ 您可以使用您的股票投资于其他公司，获得投资点数（IP）。 IP 提供了一个很大的乘数，但它会随着时间的推移而衰减。",
    "Gain more money based on money.": "根据金钱获得更多金钱。",
    "Investment points decay slower.": "投资点衰减较慢。",
    "Stability": "稳定性",
    "Synergy": "协同效应",
    "Sometimes your employees aren't happy (for those that slack on work when unhappy, they are fired immediately). That's okay! However, making your employees happier can increase their productivity. So try to spread a little joy!": "有时您的员工不开心（对于那些在不开心时工作松懈的人，他们会立即被解雇）。 没关系！ 但是，让您的员工更快乐可以提高他们的生产力。 所以试着传播一点快乐！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Quota:": "报价：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "The morale effect is exponentiated by ": "士气效应的指数为",
    "Divide the cost of morale by ": "将士气成本除以 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^The humble Intern forms the backbone of any savvy business, paid in experience and eager to please as they pad their resumes in hopes of a better tomorrow.\nAmount Hired: (.+)\nCost: (.+)\nBase Effect: (.+)\/sec$/, '谦虚的实习生构成了任何精明业务的支柱，经验丰富，并且渴望取悦他们，因为他们填写简历以希望明天更美好。\n雇用金额：$1\n成本：$2\n基本效果：$3\/秒'],
    [/^The confident Salesman is the engine of your business, bringing your valuable products to your cash-laden customers, whether they want them or not.\nAmount Hired: (.+)\nCost: (.+)\nBase Effect: (.+)\/sec$/, '自信的推销员是您业务的引擎，无论他们是否需要，都将您有价值的产品带给现金充裕的客户。\n雇佣金额：$1\n成本：$2\n基本效果：$3\/秒'],
    [/^The solemn Wage Slave is essential to the success of any growing business, dedicated to their work and trapped in an unbreakable cycle of poverty and obligation.\nAmount Hired: (.+)\nCost: (.+)\nBase Effect: (.+)\/sec$/, '庄严的工资奴隶对于任何成长中的企业的成功都是必不可少的，他们致力于工作并陷入贫困和义务的牢不可破的循环中。\n雇佣金额：$1\n成本：$2\n基本效果：$3\/秒'],
    [/^The ambitious Middle Manager is loyal to your business, striving each day to dominate your lower employees, lest they wither from a lack of motivating leadership.\nAmount Hired: (.+)\nCost: (.+)\nBase Effect: (.+)\/sec$/, '雄心勃勃的中层经理对您的企业忠诚，每天都在努力控制您的下级员工，以免他们因缺乏激励性的领导而枯萎。\n雇用金额：$1\n成本：$2\n基本效果：$3\/秒'],
    [/^The wise C-Level is the conductor of your business, always thinking of innovative and inspiring ways to appear to meet shareholder expectations or inflate valuations.\nAmount Hired: (.+)\nCost: (.+)\nBase Effect: (.+)\/sec$/, '明智的 C级 是您业务的指挥者，总是想着创新和鼓舞人心的方式来满足股东期望或夸大估值。\n雇用金额：$1\n成本：$2\n基本效果：$3\/秒'],
    [/^The brave Privatized Cop is the defender of your business, decked out in riot gear and gas masks as the last line of defense between bricks and your windows.\nAmount Hired: (.+)\nCost: (.+)\nBase Effect: (.+)\/sec$/, '勇敢的私有化警察是您企业的捍卫者，身着防暴装备和防毒面具作为砖块和窗户之间的最后一道防线。\n雇佣金额：$1\n成本：$2\n基本效果：$3\/秒'],
    [/^The dignified Pocket Politician allows your business to thrive unburdened by certain regulations, which would otherwise choke the life from it like a worker getting too close to the conveyor belt.\nAmount Hired: (.+)\nCost: (.+)\nBase Effect: (.+)\/sec$/, '高贵的袖珍政治家可以让您的企业在不受某些法规负担的情况下蓬勃发展，否则会像工人离传送带太近一样扼杀它的生命。\n雇佣金额：$1\n成本：$2\n基本效果：$3/秒'],
    [/^The omniscient Overseer is the primordial employee of your business, part of an elusive council unspeakably powerful, hailing from a time beyond memory.\nAmount Hired:(.+)\nCost: (.+)\nBase Effect: (.+)\/sec$/, '无所不知的监督者是您企业的原始员工，是难以言喻的强大议会的一部分，来自于记忆之外的时代。\n雇佣金额：$1\n成本：$2\n基础效果：$3\/秒'],
    [/^The mysterious Shadow Government is the secret benefactor of your business, encouraging social discord and diminishing cultures as they please.\nAmount Hired: (.+)\nCost: (.+)\nBase Effect: (.+)\/sec$/, '神秘的影子政府是您业务的秘密恩人，鼓励社会不和并随心所欲地削弱文化。\n雇佣金额：$1\n成本：$2\n基础效果：$3\/秒'],
    [/^You have (.+) goals \((.+)$/, '你有 $1 个目标 \($2'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You have (.+) money$/, '你有 $1 金钱'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Next at (.+) money$/, '下一个在 $1 金钱'],
    [/^Reach (.+) money to unlock \(You have (.+) money$/, '达到 $1 金钱以解锁（你有 $1 金钱'],
    [/^Reach (.+) points with only Interns.$/, '达到 $1 点数在只有实习生的情况下。'],
    [/^Reach (.+) points.$/, '达到 $1 点数。'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) morale$/, '$1 士气'],
    [/^([\d\.,]+) stocks$/, '$1 股票'],
    [/^([\d\.,]+) training seminars$/, '$1 培训班'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) morale$/, '成本：$1 士气'],
    [/^Cost: (.+) stocks$/, '成本：$1 股票'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Cost: (.+) training seminars$/, '成本：$1 培训班'],
    [/^Req: (.+) \/ (.+) money$/, '成本：$1 \/ $2 金钱'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);